---
infra:
  - secrets
  - vpc
  - pipeline-s3
  - pipeline-cloudtrail
  - pipeline-iam
  - pipeline-webhook
  - pipeline
vpc:
  cidr: 10.2.0.0/16
  subnets:
    subnet1:
      cidr: 10.2.0.0/22
      type: public
      az: a
    subnet2:
      cidr: 10.2.4.0/22
      type: public
      az: b
    subnet3:
      cidr: 10.2.8.0/22
      type: private
      az: a
    subnet4:
      cidr: 10.2.12.0/22
      type: private
      az: b
    subnet5:
      cidr: 10.2.16.0/22
      type: private
      az: c
    subnet6:
      cidr: 10.2.20.0/22
      type: private
      az: a
k8s_clusters:
  east1:
    this: that
  west1:
    this: that
  east2:
    this: that
applications:
  auth:
    clusters:
      - east1
      - east2
  app1:
    cluster:
      - west1
      - east2
databases:
  db_name: test

